/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_company_BME280Jni */

#ifndef _Included_com_company_BME280Jni
#define _Included_com_company_BME280Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_BME280Jni
 * Method:    BME280Init
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_company_BME280Jni_BME280Init
  (JNIEnv *, jobject);

/*
 * Class:     com_company_BME280Jni
 * Method:    BME280GetData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_company_BME280Jni_BME280GetData
  (JNIEnv *, jobject);

/*
 * Class:     com_company_BME280Jni
 * Method:    BME280Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_company_BME280Jni_BME280Destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_company_BME280Jni
 * Method:    GPIOSetPin
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_company_BME280Jni_GPIOSetPin
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
